### ISSUE TITLE
🐛 [Bug] Cannot work with PyTorch 1.11.0, libcaffe2_detectron_ops_gpu.so:  No such file or directory

### ISSUE THREAD

**Issue by joshuafc** [NVIDIA/Torch-TensorRT#1023]
##  Bug Description

```
(pytorch) xxx@yyy:~/PycharmProjects/detect$ torchtrtc
torchtrtc: error while loading shared libraries: libcaffe2_detectron_ops_gpu.so: cannot open shared object file: No such file or directory
```
## To Reproduce

1. wget https://download.pytorch.org/libtorch/cu113/libtorch-cxx11-abi-shared-with-deps-1.11.0%2Bcu113.zip
2. unzip it
3. the libtorch 1.11.0 package have no `libcaffe2_detectron_ops_gpu.so`, `libcaffe2_observers.so` and `libcaffe2_module_test_dynamic.so`, cause torchtrtc not work.

pytorch 1.8.2 has these libs and work fine.

**Comment by narendasan** [comment]
How did you install Torch-TensorRT?

**Comment by joshuafc** [comment]
`pip3 install torch-tensorrt -f https://github.com/NVIDIA/Torch-TensorRT/releases`

**Comment by joshuafc** [comment]
thanks!
