### ISSUE TITLE
🐛 [Bug] Torch-TensorRT static initialisation order

### ISSUE THREAD

**Issue by gcuendet** [NVIDIA/Torch-TensorRT#1035]
This isn't directly a bug in itself, but rather a suboptimal design of the core_runtime library that can lead to bugs (such as the one [discussed here](https://github.com/NVIDIA/Torch-TensorRT/discussions/1007#discussioncomment-2697538)).

##  Bug Description

In `register_trt_op.cpp`, the core_runtime library registers the `execute_engine` function in torch, using the `TORCH_LIBRARY` macro.
```
// declaration of execute_engine added here for readability
std::vector<at::Tensor> execute_engine(std::vector<at::Tensor> inputs, c10::intrusive_ptr<TRTEngine> compiled_engine);

TORCH_LIBRARY(tensorrt, m) {
  m.def("execute_engine", execute_engine);
}
```

This macro results in a bunch of static object initialisation. But more importantly, it relies on the `TRTEngine` type to be known by torch _already_! This registration is happening in `TRTEngine.cpp` (note that this is a _different_ translation unit!) with the instantiation of a static torch::class_<TRTEngine>:
```
static auto TORCHTRT_UNUSED TRTEngineTSRegistrtion =
    torch::class_<TRTEngine>("tensorrt", "Engine")
```

Static initialisations order across translation units is known to be _undefined_. Relying on that order is referred to as [static initialisation order fiasco](https://en.cppreference.com/w/cpp/language/siof) and is a bad idea in general.

## To Reproduce

1. Switch the order of the files `TRTEngine.cpp` and `register_trt_op.cpp` in `core/runtime/BUILD`, recompile, and try to run anything.

```
cc_library(
    name = "runtime",
    srcs = [
        "CudaDevice.cpp",
        "DeviceList.cpp",
        "register_trt_op.cpp",
        "TRTEngine.cpp",  # <-- put this one after "register_trt_op.cpp"
        "runtime.cpp"
    ],
```

## Proposed changes

There are a few solutions to improve the design of core_runtime, the most straightforward one being to group the static initialization in the same translation unit, so that the order is actually defined.

**Comment by narendasan** [comment]
Thanks, restructured the runtime lib to hopefully avoid this
