### ISSUE TITLE
❓ __torch__.torch.classes.tensorrt.Engine what does it mean?

### ISSUE THREAD

**Issue by mjack3** [NVIDIA/Torch-TensorRT#1045]
Hello community and thanks for this repo.

## ❓ Question

How can I load a tensorRT model after using torch.jit.save?

## What you have already tried

```
import torch
model = torch.jit.load('trt_model.torch-tensorrt') # give error __torch__.torch.classes.tensorrt.Engine
```

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0): 1.10
 - CPU Architecture: x64
 - OS (e.g., Linux): 20.04
 - How you installed PyTorch: conda
 - Python version: 3.8
 - CUDA version: 11.6
 - GPU models and configuration: Nvidia RTX3090
 - Information: torchvision installed by pip3 install torch-tensorrt -f https://github.com/NVIDIA/Torch-TensorRT/releases

## Additional context

My code is very simple:

```
import torch
import torch_tensorrt

traced_model = torch.jit.trace(eager_model, [torch.rand(1, 3, 224, 224).to(device)])
trt_model = torch_tensorrt.compile(traced_model,
                                       inputs= [torch_tensorrt.Input((1, 3, 224, 224))],
                                       enabled_precisions={torch.float32})
torch.jit.save(trt_model, 'trt_model.torch-tensorrt')
model = torch.jit.load('trt_model.torch-tensorrt') # give error __torch__.torch.classes.tensorrt.Engine
```
At the end, I want to move the trt_model.torch-tensorrt file into an Jetson for load with torch.jit.load

Thanks

**Comment by f291400** [comment]
I try torch.jit.load, it works
![image](https://user-images.githubusercontent.com/13358476/167623556-45349841-0d59-46b8-8639-34df15912d68.png)

**Comment by mjack3** [comment]
Well, I think the problem is in torchvision.models.feature_extraction.create_feature_extractor, which is used in my model.

This code works well
```
model = torch.hub.load('pytorch/vision:v0.10.0', 'resnet50', pretrained=True)
model.eval()

trt_model_fp32 = torch_tensorrt.compile(model, inputs = [torch_tensorrt.Input((128, 3, 224, 224), dtype=torch.float32)],
    enabled_precisions = torch.float32, # Run with FP32
)

torch.jit.save(trt_model_fp32, 'export/sample.trt')
trt_model_fp32 = torch.jit.load('export/sample.trt').cuda()
```
This code doesn't work
```
import torch
import torch_tensorrt
from torchvision.models.feature_extraction import create_feature_extractor

**model = torch.hub.load('pytorch/vision:v0.10.0', 'resnet50', pretrained=True)
model = create_feature_extractor(model,
                                          {f'layer{k}': str(i) for i,k in enumerate([2, 3])})**

model.eval()

trt_model_fp32 = torch_tensorrt.compile(model, inputs = [torch_tensorrt.Input((128, 3, 224, 224), dtype=torch.float32)],
    enabled_precisions = torch.float32, # Run with FP32
)

torch.jit.save(trt_model_fp32, 'export/sample.trt')
trt_model_fp32 = torch.jit.load('export/sample.trt').cuda()
```

it either

**model = torch.hub.load('pytorch/vision:v0.10.0', 'resnet50', pretrained=True)
model = create_feature_extractor(model,
                                          {f'layer{k}': str(i) for i,k in enumerate([2, 3])})
model.eval()
model = torch.jit.trace(model, [torch.rand(1, 3, 224, 224)], strict=False)
**



trt_model_fp32 = torch_tensorrt.compile(model, inputs = [torch_tensorrt.Input((128, 3, 224, 224), dtype=torch.float32)],
    enabled_precisions = torch.float32, # Run with FP32
)

torch.jit.save(trt_model_fp32, 'export/sample.trt')
trt_model_fp32 = torch.jit.load('export/sample.trt').cuda()

**Comment by mjack3** [comment]
Wel..not it's works.

I don't know why x)

**Comment by vinthony** [comment]
add `import torch_tensorrt` works for me
