### ISSUE TITLE
can torch-tensorrt-1.1.0 support libtorch1.9 and cuda10.2?

### ISSUE THREAD

**Issue by f291400** [NVIDIA/Torch-TensorRT#1047]
## ❓ Question

I want to know if torch-tensorrt-1.1.0 can be compiled with libtorch1.9 and cuda-10.2 ?

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - PyTorch Version (e.g., 1.9.0):
 - CPU Architecture: x86
 - OS (e.g., Linux): linux
 - CUDA version:10.2
 - GPU models and configuration:T4

**Comment by f291400** [comment]
I try to compile it,  but bazel max-version is 4.2.1 , lower than 5.1 needed in torch-tensorrt, on linux  platform.

**Comment by narendasan** [comment]
Not out of the box. You can backport the 1.1 source code to 1.9 if you'd like (we can provide guidance on how to do so) but because TorchScript changes so often we need to target specific minor versions.
