### ISSUE TITLE
🐛 [Bug] source code compile error

### ISSUE THREAD

**Issue by f291400** [NVIDIA/Torch-TensorRT#1053]
##  Bug Description

bazel compile error.
![image](https://user-images.githubusercontent.com/13358476/167786182-80d4636e-75bf-484b-977a-77764bc591d5.png)

## To Reproduce

1. change WORKSPACE
![image](https://user-images.githubusercontent.com/13358476/167787006-816359ca-5d45-488a-9504-72b3f6e962d8.png)
![image](https://user-images.githubusercontent.com/13358476/167787056-583370e8-0c4a-4b08-9928-35a9e602a592.png)

2.change tensort (fix address problem)
![image](https://user-images.githubusercontent.com/13358476/167787243-2bb6072d-ee52-47b9-8cbb-857c6631a2ca.png)

3. change cudnn (fix address problem)
![image](https://user-images.githubusercontent.com/13358476/167787341-2aa4b54b-455e-4a26-ba3c-b8e910ae47c2.png)

4. compile
 use gcc-7.3.0 
 bazel build //:libtorchtrt --compilation_mode opt

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version:1.1.0
 - LibTorch Version:1.9.0 (compiled with source-code(v1.9.0) by myself)
 - OS:linux
 - CUDA version:cuda10.2
 - GPU models and configuration:1/2 T4
 - TensorRT: tensorRT-8.2.4.2
 - Cudnn: v8.2.1.32 (already copy to cuda directory)
 -

**Comment by andi4191** [comment]
The compilation error is due to torch API update in 1.10.0

you are using older version of libtorch with torch-tensorrt v1.1.0. Please refer to the release page for correct dependency version

**Comment by andi4191** [comment]
If you are attempting to use old version of libtorch as mentioned in #1047  you need to backport 1.1.0 code base.

**Comment by f291400** [comment]
> If you are attempting to use old version of libtorch as mentioned in #1047 you need to backport 1.1.0 code base.

OK, thanks
