### ISSUE TITLE
↔ [Converter] Add support for aten::affine_grid_generator in TRTorch

### ISSUE THREAD

**Issue by zccyman** [NVIDIA/Torch-TensorRT#261]
##

- **Function Schema**: aten::affine_grid_generator(Tensor theta, int[] size, bool align_corners) -> (Tensor)

- **Original PyTorch API**: https://pytorch.org/docs/stable/_modules/torch/nn/functional.html#affine_grid

**Comment by peri044** [comment]
There's no native op in TensorRT which supports this. You would have to implement the plugin and integrate with TRTorch.
Some useful resources 
- https://github.com/NVIDIA/TRTorch/blob/master/core/conversion/converters/impl/plugins/interpolate_plugin.h
- https://github.com/NVIDIA/TRTorch/blob/master/core/conversion/converters/impl/interpolate.cpp

Let us know if you have any issues while integrating.

**Comment by abhigoku10** [comment]
@zccyman  any update on this thread ??where you able to convert
