### ISSUE TITLE
Merge RemoveContiguous with RemoveNOP 

### ISSUE THREAD

**Issue by narendasan** [NVIDIA/Torch-TensorRT#441]
We can probably move RemoveContiguous to RemoveNOP:

https://github.com/NVIDIA/TRTorch/blob/72cb449166a885974c619e4040e38801dd61ae02/core/lowering/passes/remove_contiguous.cpp#L10

**Comment by himanshu007-creator** [comment]
We have to migrate this function <a href="https://github.com/NVIDIA/TRTorch/blob/72cb449166a885974c619e4040e38801dd61ae02/core/lowering/passes/remove_nops.cpp">here</a> and then delete <a href="https://github.com/NVIDIA/TRTorch/blob/72cb449166a885974c619e4040e38801dd61ae02/core/lowering/passes/remove_contiguous.cpp">this file</a> right?

correct me if i am wrong here. I would like to work on this issue.

**Comment by narendasan** [comment]
Yeah I think that should be it. We would also need a new test that makes sure that the graph transform we used to do in RemoveContiguous works in the same way through RemoveNOP
