### ISSUE TITLE
❓ [Question] Are there plans to support TensorRT 8 and Ubuntu 20.04? 

### ISSUE THREAD

**Issue by danielgordon10** [NVIDIA/Torch-TensorRT#519]

**Comment by narendasan** [comment]
Yes, we will support TensorRT 8 in the next release (v0.4.0). You can track work for that here: https://github.com/NVIDIA/TRTorch/pull/503. For 20.04, I are you currently seeing issues with 20.04? I think we will change our base development OS as the default OS gets updated for various platforms within NVIDIA, such as CUDA, TensorRT, Jetson, etc (CUDA and TensorRT are already on 20.04 I believe).

**Comment by narendasan** [comment]
cc: @andi4191 for CI/CD we might want to look at adding 20.04 as a target

**Comment by danielgordon10** [comment]
20.04 doesn't have any TensorRT 7 apt files. I tried installing the 18.04 apt files, but ran into issues with other nvidia libraries. For context I am using the NVidia docker for Ubuntu 20.04 with CUDNN built in.

**Comment by narendasan** [comment]
Are you trying to use a 20.04 based container or is the base os 20.04? Perhaps using an NGC container might help as a base if you have flexibility in choice there. They have most of the NVIDIA libraries preinstalled. I believe we recommend people to use nvcr.io/nvidia/pytorch:21.02-py3 or nvcr.io/nvidia/pytorch:21.03-py3 as a base for TRTorch containers (you can find a recipe in //docker).

**Comment by danielgordon10** [comment]
Our base is nvidia/cuda:11.1-cudnn8-devel-ubuntu20.04. We want flexibility to install different versions of Pytorch, but we could consider switching to a container with pytorch pre-installed.

**Comment by narendasan** [comment]
You don't necessarily need to use the PyTorch NGC container but it and the tensorrt NGC containers have all CUDA libraries including TensorRT installed and validated together. Maybe if you want flexibility for PyTorch, the tensorrt containers would be a better choice.

**Comment by narendasan** [comment]
@ncomly-nvidia We probably need to discuss what our base os target will be moving forward

**Comment by danielgordon10** [comment]
Using the container you recommended I still have issues


```
docker run --gpus all -it --rm -v /home/daniel:/daniel nvcr.io/nvidia/pytorch:21.02-py3
root@32f3e61095c6:/workspace# pip3 install trtorch -f https://github.com/NVIDIA/TRTorch/releases
Looking in links: https://github.com/NVIDIA/TRTorch/releases
Collecting trtorch
  Downloading https://github.com/NVIDIA/TRTorch/releases/download/v0.4.1/trtorch-0.4.1-cp38-cp38-linux_x86_64.whl (7.6 MB)
     |████████████████████████████████| 7.6 MB 10.9 MB/s
Installing collected packages: trtorch
Successfully installed trtorch-0.4.1
root@32f3e61095c6:/workspace# python
Python 3.8.5 (default, Sep  4 2020, 07:30:14)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
>>> torch.zeros(10).cuda()
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], device='cuda:0')
>>> import trtorch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/trtorch/__init__.py", line 11, in <module>
    from trtorch._compiler import *
  File "/opt/conda/lib/python3.8/site-packages/trtorch/_compiler.py", line 5, in <module>
    import trtorch._C
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
>>>

**Comment by narendasan** [comment]
This seems like a version mismatch between what TRTorch targets and what is shipped in the container, one of the pitfalls with using the PyTorch NGC containers as a base is they use a different ABI than the official PyTorch.org builds. The github precompiled releases are designed to work with the PyTorch.org builds. NGC containers also build the master branch of PyTorch circa when they are built so usually while the official version of PyTorch is 1.x, NGC is on 1.(x + 1). I recommend you use the Dockerfile in //docker as a final layer on whatever base container best suits your usecase. It should work as long as TensorRT, cudnn , pytorch and cuda are all pre-installed.  

So if you want to use PyTorch 21.02 you should be able to run 
```
docker build -t trtorch --build-arg BASE=21.02 --network=host -f docker/Dockerfile .
```

If you want to use a custom container (or any non-pytorch-ngc container) you can do 
```
docker build -t trtorch:21.09 --build-arg BASE_IMG=<MY BASE IMAGE>--network=host -f docker/Dockerfile .
```

Also in the case you use a non PyTorch NGC container and you install PyTorch from PyTorch.org you might need to edit the dist-build.sh script to remove the `--use-cxx11-abi` flag

https://github.com/NVIDIA/TRTorch/blob/f99a6ca763eb08982e8b7172eb948a090bcbf11c/docker/dist-build.sh#L7 

Not sure if that fully answers your question but I think this is probably the best path to head down to get TRTorch in an arbitrary container. Feel free to tag me if you are still having problems
