### ISSUE TITLE
🐛 [Bug] Encountered bug " Expected ivalue->isInt() to be true but got fals " when using TRTorch

### ISSUE THREAD

**Issue by JuncFang-git** [NVIDIA/Torch-TensorRT#585]
##  Bug Description
I got a bug when converting an operation :
`
h, w = spatial_size
x = torch.arange(w).type(type)
y = torch.arange(h).type(type)
`

Where spatial_size is a tensor's shape like:  spatial_size = a.shape[2:]

It works when I change the size value (h, w) to int:
`
h, w = spatial_size
h, w = int(h), int(w)
x = torch.arange(w).type(type)
y = torch.arange(h).type(type)
`

The bug info:
terminate called after throwing an instance of 'trtorch::Error'
  what():  [Error thrown at ./core/conversion/var/Var_inl.h:38] Expected ivalue->isInt() to be true but got false
Requested unwrapping of arg IValue assuming it was l however type is NoneType

## To Reproduce

1. h, w = tensor.shape[2:] , lots of function use h, w. like torch.arange(w)
1. Is ok when set : h, w = int(h), int(w)

## Expected behavior

Fix this bug and merge to master branch. Or make sure it is no problem.

## Environment

> I build the Trtorch recently(21.8.19) use the master branch.

 - TRTorch Version (8.0.1.6): 
 - PyTorch Version (libtorch 1.9.0):
 - OS (Ubuntu):
 - How you installed PyTorch (`libtorch):
 - Build command you used (bazel build //:libtrtorch --compilation_mode opt):
 - Are you using local sources or building from archives:
 - Python version: 3.8
 - CUDA version: 11.1
 - GPU models and configuration: GTX3070

## Additional context
I compile the model use below code:
`std::cout << "Load ts detector model ..." << std::endl;
    torch::jit::Module ts_detector_model;
    try{
        ts_detector_model = torch::jit::load(TS_DETECTOR_PATH);
    }
    catch (const c10::Error& e){
        std::cerr << "Error loading the model \n";
        return -1;
    }

    // convert trt detector
    std::cout << "Convert trt detector model ..." << std::endl;
    ts_detector_model.to(at::kCUDA);
    ts_detector_model.eval();

    std::vector<trtorch::CompileSpec::Input> inputs_d = {
      trtorch::CompileSpec::Input(std::vector<int64_t>({1, 3, 256, 256}), trtorch::CompileSpec::DataType::kHalf)};
    auto info_d = trtorch::CompileSpec(inputs_d);
    info_d.enabled_precisions.insert(trtorch::CompileSpec::DataType::kHalf);

    auto trt_detector_model = trtorch::CompileGraph(ts_detector_model, info_d);`

**Comment by narendasan** [comment]
Can you provide us the debug logs here or a minimal reproducing example, It will let us figure out exactly where this error is coming from
