### ISSUE TITLE
🐛 [Bug] add slice layer in dynamic batch size

### ISSUE THREAD

**Issue by MichealZhang** [NVIDIA/Torch-TensorRT#614]
## To Reproduce

ERROR: [TRTorch Conversion Context] - (Unnamed Layer* 186) [Slice]: ISliceLayer size elements must be non-negative, but size on axis 0 is not
ERROR: [TRTorch Conversion Context] - Builder failed while analyzing shapes.
terminate called after throwing an instance of 'trtorch::Error'
  what():  [Error thrown at /home/xxx/trtorch/core/conversion/conversionctx/ConversionCtx.cpp:164] Building TensorRT engine failed

## Environment

> Build information about the TRTorch compiler can be found by turning on debug messages

 - TRTorch Version (e.g. 0.2.0):  0.41
 - PyTorch Version (e.g. 1.0): 1.9
 - CPU Architecture:
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source):
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version:
 - CUDA version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by narendasan** [comment]
Can you provide a reproducing example? This error is coming from TensorRT so there might not be anything we can do

**Comment by peri044** [comment]
@MichealZhang  Have you resolved this issue ? or can you provide us a reproducer for us to test this ?

**Comment by MichealZhang** [comment]
> @MichealZhang Have you resolved this issue ? or can you provide us a reproducer for us to test this ?

I update the converter select.cpp in my project, because i found that TRT Slice layers performs better than Gather layer. Here is my code:

//
// Created by zhang on 2021/8/23.
//
#include <ATen/ATen.h>
#include <vector>
#include "NvInfer.h"
#include "c10/util/intrusive_ptr.h"
#include "core/conversion/converters/converter_util.h"
#include "core/conversion/converters/converters.h"
#include "core/conversion/tensorcontainer/TensorContainer.h"
#include "core/util/prelude.h"
#include "torch/torch.h"

namespace trtorch {
namespace core {
namespace conversion {
namespace converters {
namespace impl {
namespace {

bool add_split(ConversionCtx* ctx, const torch::jit::Node* n, args& args, bool split_list) {
  auto in = args[0].ITensor();
  auto axis = args[2].unwrapToInt();
  auto inDimSize = in->getDimensions().d[axis];
  auto numOutputs = 1, numRemainder = 0;
  std::vector<int64_t> sizes;

  if (split_list) {
    sizes = args[1].unwrapToIntList().vec();
    numOutputs = sizes.size();
  } else {
    auto split_size = args[1].unwrapToInt();
    numOutputs = inDimSize / split_size;
    numRemainder = inDimSize % split_size;
    for (int64_t i = 0; i < numOutputs; i++) {
      sizes.push_back(split_size);
    }
    if (numRemainder) {
      numOutputs += 1;
      sizes.push_back(numRemainder);
    }
  }

  c10::ListTypePtr lt = n->output()->type()->expect<c10::ListType>();
  c10::TypePtr elementType = lt->getElementType();
  auto list = c10::impl::GenericList(elementType);
  list.reserve(numOutputs);

  int start_idx = 0;
  for (int i = 0; i < numOutputs; i++) {
    bool neg = false;
    nvinfer1::Dims start_(in->getDimensions()), size_(in->getDimensions()), stride_(in->getDimensions());
    for (int32_t j = 0; j < start_.nbDims; j++) {
      if (j == axis) {
        start_.d[j] = start_idx;
        size_.d[j] = sizes[i];
      }
      else {
        start_.d[j] = 0;
        size_.d[j] = in->getDimensions().d[j];
      }
      stride_.d[j] = 1;
      if (in->getDimensions().d[j] < 1)
        neg = true;
    }

    auto slice_layer = ctx->net->addSlice(*in, start_, size_, stride_);
    if (neg == true) {
      auto size_tmp = torch::tensor(util::toVec(size_), torch::kInt32);
      auto size_new = tensor_to_const(ctx, size_tmp);
      slice_layer->setInput(2, *size_new);
    }

    auto slice_out = slice_layer->getOutput(0);
    if (neg == true) {
      auto in_shuffle = ctx->net->addShuffle(*slice_out);
      in_shuffle->setReshapeDimensions(size_);
      slice_out = in_shuffle->getOutput(0);
    }

    auto tensor_holder = TensorContainer();
    tensor_holder.hold_tensor(slice_out);
    auto ival = c10::IValue(std::move(c10::make_intrusive<TensorContainer>(tensor_holder)));
    list.emplace_back(ival);

    start_idx = start_idx + sizes[i];
  }

  auto split_output_ivalue = std::move(torch::jit::IValue(list));
  ctx->AssociateValueAndIValue(n->outputs()[0], split_output_ivalue);

  return true;
}

auto select_registrations TRTORCH_UNUSED =
    RegisterNodeConversionPatterns()
        .pattern({"aten::select.int(Tensor(a) self, int dim, int index) -> (Tensor(a))",
                  [](ConversionCtx* ctx, const torch::jit::Node* n, args& args) -> bool {
                    auto in = args[0].ITensorOrFreeze(ctx);
                    auto maxDim = static_cast<int64_t>(in->getDimensions().nbDims);
                    auto dim = args[1].unwrapToInt();
                    // Handle negative axis by refering to nbDims of input Tensor
                    dim = dim < 0 ? dim + maxDim : dim;
                    auto ind = (int32_t)args[2].unwrapToInt();
                    // Along the specified dimension, handle negative index by subtracting along length of dimension.
                    ind = ind < 0 ? ind + in->getDimensions().d[dim] : ind;
                    LOG_DEBUG("Slice input dimensions: " << in->getDimensions());
                    LOG_DEBUG("Dimension to select: " << dim);
                    LOG_DEBUG("Index: " << ind);

                    nvinfer1::Dims start_(in->getDimensions()), size_(in->getDimensions()), stride_(in->getDimensions());

                    for (int32_t i = 0; i < start_.nbDims; i++) {
                      if (i == dim) {
                        start_.d[i] = ind;
                        size_.d[i] = 1;
                      }
                      else {
                        start_.d[i] = 0;
                        size_.d[i] = in->getDimensions().d[i];
                      }
                      stride_.d[i] = 1;
                    }

                    auto slice_layer = ctx->net->addSlice(*in, start_, size_, stride_);
                    TRTORCH_CHECK(slice_layer, "Unable to slice gather layer from node: " << *n);
                    auto out = slice_layer->getOutput(0);

                    LOG_DEBUG("Slice tensor shape: " << out->getDimensions());

                    if (out->getDimensions().nbDims != 1) {
                      // IShuffleLayer removes redundant dimensions
                      auto shuffle_layer = ctx->net->addShuffle(*out);
                      TRTORCH_CHECK(shuffle_layer, "Unable to create shuffle layer from node: " << *n);
                      shuffle_layer->setReshapeDimensions(util::squeezeDims(out->getDimensions(), dim));
                      shuffle_layer->setName(util::node_info(n).c_str());
                      out = shuffle_layer->getOutput(0);
                    }

                    out = ctx->AssociateValueAndTensor(n->outputs()[0], out);

                    LOG_DEBUG("Output tensor shape: " << out->getDimensions());

                    return true;
                  }})
        .pattern({"aten::narrow(Tensor(a) self, int dim, int start, int length) -> Tensor(a)",
                  [](ConversionCtx* ctx, const torch::jit::Node* n, args& args) -> bool {
                    auto in = args[0].ITensor();
                    auto axis = args[1].unwrapToInt();
                    auto start = (int32_t)args[2].unwrapToInt();
                    auto length = (int32_t)args[3].unwrapToInt();

                    nvinfer1::Dims start_(in->getDimensions()), size_(in->getDimensions()), stride_(in->getDimensions());

                    for (int32_t i = 0; i < start_.nbDims; i++) {
                      if (i == axis) {
                        start_.d[i] = start;
                        size_.d[i] = length;
                      }
                      else {
                        start_.d[i] = 0;
                        size_.d[i] = in->getDimensions().d[i];
                      }
                      stride_.d[i] = 1;
                    }

                    auto slice_layer = ctx->net->addSlice(*in, start_, size_, stride_);
                    TRTORCH_CHECK(slice_layer, "Unable to create slice layer from node: " << *n);
                    auto slice_out = slice_layer->getOutput(0);

                    // IShuffleLayer removes redundant dimensions
                    auto shuffle_layer = ctx->net->addShuffle(*slice_out);
                    TRTORCH_CHECK(shuffle_layer, "Unable to create shuffle layer from node: " << *n);
                    shuffle_layer->setReshapeDimensions(util::unpadDims(slice_out->getDimensions()));
                    shuffle_layer->setName(util::node_info(n).c_str());
                    auto shuffle_out = shuffle_layer->getOutput(0);

                    auto out = ctx->AssociateValueAndTensor(n->outputs()[0], shuffle_out);

                    LOG_DEBUG("Output tensor shape: " << out->getDimensions());

                    return true;
                  }})
        .pattern({"aten::narrow.Tensor(Tensor(a) self, int dim, Tensor start, int length) -> Tensor(a)",
                  [](ConversionCtx* ctx, const torch::jit::Node* n, args& args) -> bool {
                    auto in = args[0].ITensor();
                    auto axis = args[1].unwrapToInt();
                    torch::Tensor start = args[2].IValue()->toTensor().to(torch::kI32);
                    int32_t startIdx = start.item().to<int32_t>();
                    auto length = (int32_t)args[3].unwrapToInt();

                    nvinfer1::Dims start_(in->getDimensions()), size_(in->getDimensions()), stride_(in->getDimensions());

                    for (int32_t i = 0; i < start_.nbDims; i++) {
                      if (i == axis) {
                        start_.d[i] = startIdx;
                        size_.d[i] = length;
                      }
                      else {
                        start_.d[i] = 0;
                        size_.d[i] = in->getDimensions().d[i];
                      }
                      stride_.d[i] = 1;
                    }

                    auto slice_layer = ctx->net->addSlice(*in, start_, size_, stride_);
                    TRTORCH_CHECK(slice_layer, "Unable to slice gather layer from node: " << *n);
                    auto slice_out = slice_layer->getOutput(0);

                    // IShuffleLayer removes redundant dimensions
                    auto shuffle_layer = ctx->net->addShuffle(*slice_out);
                    TRTORCH_CHECK(shuffle_layer, "Unable to create shuffle layer from node: " << *n);
                    shuffle_layer->setReshapeDimensions(util::unpadDims(slice_out->getDimensions()));
                    shuffle_layer->setName(util::node_info(n).c_str());
                    auto shuffle_out = shuffle_layer->getOutput(0);

                    auto out = ctx->AssociateValueAndTensor(n->outputs()[0], shuffle_out);

                    LOG_DEBUG("Output tensor shape: " << out->getDimensions());

                    return true;
                  }})
        .pattern(
            {"aten::embedding(Tensor weight, Tensor indices, int padding_idx=-1, bool scale_grad_by_freq=False, bool sparse=False) -> (Tensor)",
             [](ConversionCtx* ctx, const torch::jit::Node* n, args& args) -> bool {
               auto embeddingTensor = args[0].ITensorOrFreeze(ctx);
               auto indicesTensor = args[1].ITensorOrFreeze(ctx);
               // Set datatype for indices tensor to INT32
               auto identity = ctx->net->addIdentity(*indicesTensor);
               identity->setOutputType(0, nvinfer1::DataType::kINT32);
               indicesTensor = identity->getOutput(0);

               // IGatherLayer takes in input tensor, the indices, and the axis of input tensor to take indices from
               auto gather_layer = ctx->net->addGather(*embeddingTensor, *indicesTensor, 0);
               TRTORCH_CHECK(gather_layer, "Unable to create gather layer from node: " << *n);
               auto gather_out = gather_layer->getOutput(0);

               auto out = ctx->AssociateValueAndTensor(n->outputs()[0], gather_out);

               LOG_DEBUG("Output tensor shape: " << out->getDimensions());

               return true;
             }})
        .pattern(
            {"aten::slice.Tensor(Tensor(a) self, int dim=0, int? start=None, int? end=None, int step=1) -> Tensor(a)",
             [](ConversionCtx* ctx, const torch::jit::Node* n, args& args) -> bool {
               auto in = args[0].ITensorOrFreeze(ctx);
               auto axis = args[1].unwrapToInt();
               auto maxDim = static_cast<int64_t>(in->getDimensions().d[axis]);
               auto startIdx = 0;
               auto startIdxIVal = args[2].IValue();
               if (!startIdxIVal->isNone()) {
                 startIdx = startIdxIVal->toInt();
               }
               // Handle case when given tensor index is negative
               auto start = (startIdx < 0) ? (maxDim + startIdx) : startIdx;
               // Bound the end index to input tensor dimensions at specified axis
               auto endIdx = maxDim;
               auto endIdxIVal = args[3].IValue();
               if (!endIdxIVal->isNone()) {
                 endIdx = std::min(endIdxIVal->toInt(), maxDim);
               }
               auto end = (endIdx < 0) ? (maxDim + endIdx) : endIdx;
               auto step = args[4].unwrapToInt();

               LOG_DEBUG("Start idx: " << start);
               LOG_DEBUG("End idx: " << end);

               nvinfer1::Dims start_(in->getDimensions()), size_(in->getDimensions()), stride_(in->getDimensions());

               for (int32_t i = 0; i < start_.nbDims; i++) {
                 if (i == axis) {
                   start_.d[i] = start;
                   size_.d[i] = end - start;
                 }
                 else {
                   start_.d[i] = 0;
                   size_.d[i] = in->getDimensions().d[i];
                 }
                 stride_.d[i] = step;
               }

               auto slice_layer = ctx->net->addSlice(*in, start_, size_, stride_);
               TRTORCH_CHECK(slice_layer, "Unable to create slice layer from node: " << *n);
               auto slice_out = slice_layer->getOutput(0);

               auto out = ctx->AssociateValueAndTensor(n->outputs()[0], slice_out);

               LOG_DEBUG("Slice layer output shape: " << out->getDimensions());

               return true;
             }})
        .pattern({"aten::split(Tensor self, int[] split_sizes, int dim=0) -> (Tensor[])",
                  [](ConversionCtx* ctx, const torch::jit::Node* n, args& args) -> bool {
                    add_split(ctx, n, args, true);
                    LOG_DEBUG("Converted split op into a list of IValues");
                    return true;
                  }})
        .pattern({"aten::split.Tensor(Tensor(a) self, int split_size, int dim=0) -> (Tensor[])",
                  [](ConversionCtx* ctx, const torch::jit::Node* n, args& args) -> bool {
                    add_split(ctx, n, args, false);
                    LOG_DEBUG("Converted split op into a list of IValues");
                    return true;
                  }})
        .pattern({"aten::split_with_sizes(Tensor(a) self, int[] split_sizes, int dim=0) -> (Tensor[])",
                  [](ConversionCtx* ctx, const torch::jit::Node* n, args& args) -> bool {
                    add_split(ctx, n, args, true);
                    LOG_DEBUG("Converted split op into a list of IValues");
                    return true;
                  }})
        .pattern({"aten::masked_fill.Scalar(Tensor self, Tensor mask, Scalar value) -> (Tensor)",
                  [](ConversionCtx* ctx, const torch::jit::Node* n, args& args) -> bool {
                    auto self = args[0].ITensorOrFreeze(ctx);
                    auto mask = args[1].ITensorOrFreeze(ctx);
                    mask = addPadding(ctx, n, mask, self->getDimensions().nbDims, false, true);
                    auto val = args[2].unwrapToScalar().to<float>();
                    auto val_t = tensor_to_const(ctx, torch::full(util::toVec(self->getDimensions()), val));

                    TRTORCH_CHECK(
                        util::broadcastable(self->getDimensions(), mask->getDimensions(), /*multidirectional=*/false),
                        "Self and mask tensors are not broadcastable");

                    auto new_layer = ctx->net->addSelect(*mask, *val_t, *self);
                    TRTORCH_CHECK(new_layer, "Unable to create layer for aten::masked_fill");

                    new_layer->setName(util::node_info(n).c_str());

                    auto out_tensor = ctx->AssociateValueAndTensor(n->outputs()[0], new_layer->getOutput(0));
                    LOG_DEBUG("Output shape: " << out_tensor->getDimensions());
                    return true;
                  }});

} // namespace
} // namespace impl
} // namespace converters
} // namespace conversion
} // namespace core
} // namespace trtorch


I try to split a tensor with dynamic batch size, but the param reports an error, it seems to the shape of batch size is -1

**Comment by narendasan** [comment]
Wait so for this issue @MichealZhang  did you reimplement the slice converter with ISlice and then found the bug or is this an issue with the canonical converter?
