### ISSUE TITLE
❓ [Question] Is it possible to install TRTorch with CUDA 11.1 support on aarch64?

### ISSUE THREAD

**Issue by lppllppl920** [NVIDIA/Torch-TensorRT#620]
# ❓ Question
is there a particular reason why there is no pre-built wheel file for the combination of CUDA11.1 + aarch64

# What you have already tried
I have tried to install wheel files for CUDA 10.2 aarch64 but it obviously didn't work because it tried to find the CUDA 10.2 libraries.

# Environment

> Build information about the TRTorch compiler can be found by turning on debug messages

- PyTorch Version (e.g., 1.0): 1.9.0
- CPU Architecture: 8.6
- OS (e.g., Linux): Linux
- How you installed PyTorch (conda, pip, libtorch, source): pip
- Build command you used (if compiling from source): pip install
- Are you using local sources or building from archives: building from archives
- Python version: 3.6
- CUDA version: 11.1
- GPU models and configuration: Nvida RTX 6000
- Any other relevant information: N/A

My question would be, is there a particular reason why there is no pre-built wheel file for the combination of CUDA11.1 + aarch64?

Thank you!

**Comment by narendasan** [comment]
Are you using an RTX 6000 with an ARM processor? Can you provide more system details? I assume this is not some variant of a Tegra processor? Are you able to compile locally? If so I'd assume for the most part the x86 style instructions should work as long as you have an aarch64 host compiler

**Comment by narendasan** [comment]
> is there a particular reason why there is no pre-built wheel file for the combination of CUDA11.1 + aarch64

As to the reason. This has not a very common configuration (I think this is the first report we have gotten for arm other than jetson). We have a set up for jetson since that's a pretty common use case for us. I don't think we will be shipping precompiled binaries for sbsa for a while but we are definitely interested in making the compilation experience way nicer if you are hitting issues.
