### ISSUE TITLE
🐛 [Bug] Can't convert fasterrcnn

### ISSUE THREAD

**Issue by shiyongming** [NVIDIA/Torch-TensorRT#628]
## To Reproduce

```
import math
from PIL import Image
import requests
import matplotlib.pyplot as plt
import torch
import torchvision
from torch import nn
import torchvision.transforms as T

model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True)
model.to("cuda").eval();
script_model = torch.jit.script(model)

import trtorch
script_model.to("cuda").eval()
trt_model = trtorch.compile(script_model, {
    "inputs": [trtorch.Input((1, 3, 640, 480))],
    "enabled_precisions": {torch.float, torch.half}, # Run with FP16
    "workspace_size": 1 << 20
})

```

RuntimeError: 
temporary: the only valid use of a module is looking up an attribute but found  = prim::SetAttr[name="_has_warned"](%self, %171)
:
## Environment

> Build information about the TRTorch compiler can be found by turning on debug messages

 - TRTorch Version (e.g. 0.2.0): 0.4.0
 - PyTorch Version (e.g. 1.0): 1.9
 - CPU Architecture: T4
 - OS (e.g., Linux): Ubuntu18.04
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): nvcr.io/nvidia/pytorch:21.06-py3
 - Build command you used (if compiling from source): using dockerfile.21.07(change the pytorch:21.07-py3 into pytorch:21.06)
 - Are you using local sources or building from archives:
 - Python version:
 - CUDA version: 11.3
 - GPU models and configuration:
 - Any other relevant information:

**Comment by peri044** [comment]
This is not a TRTorch bug but rather a model scripting bug. Looks like detectron supports export to torchscript. Can you refer to https://detectron2.readthedocs.io/en/latest/tutorials/deployment.html and see if you can resolve your export to torchscript issues  ?
