### ISSUE TITLE
🐛 [Bug] cannot build docker image @ v.0.1.0

### ISSUE THREAD

**Issue by yoshida-ryuhei** [NVIDIA/Torch-TensorRT#650]
##  Bug Description
- I cannot build docker image @ v.0.1.0.

## To Reproduce
1. switch to v.0.1.0
1. docker build -f docker/Dockerfile.20.07 . 
I receive these errors.
```
The following additional packages will be installed:
  dirmngr gnupg-l10n gnupg-utils gpg gpg-agent gpg-wks-client gpg-wks-server
  gpgconf gpgsm gpgv libcurl4
Suggested packages:
  dbus-user-session libpam-systemd pinentry-gnome3 tor parcimonie xloadimage
  scdaemon
The following packages will be upgraded:
  curl dirmngr gnupg gnupg-l10n gnupg-utils gpg gpg-agent gpg-wks-client
  gpg-wks-server gpgconf gpgsm gpgv libcurl4
13 upgraded, 0 newly installed, 0 to remove and 86 not upgraded.
Need to get 2529 kB of archives.
After this operation, 26.6 kB of additional disk space will be used.
Do you want to continue? [Y/n] Abort.
The command '/bin/sh -c apt-get update && apt-get install curl gnupg  && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 1
```

## Expected behavior
- I can build docker image without error.

## Environment
 - TRTorch Version : None
 - PyTorch Version : None
 - CPU Architecture:  x86_64
 - OS (e.g., Linux):  Linux archlinux 5.14.8-arch1-1
 - How you installed PyTorch:None
 - Build command you used (if compiling from source): docker build
 - Are you using local sources or building from archives: None
 - Python version: 3.9.7 (gcc 11.1.0)
 - CUDA version: 11.4
 - GPU models and configuration: 3070Ti (PALIT 3070TI GAMING PRO)
 - Docker version: 20.10.8, build 3967b7d
 - nvidia-container-cli version: 1.4.0 

## Additional context
- I have written a code in [my fork repository](https://github.com/yoshida0112/TRTorch/tree/dev/improve_v0.1.0) to fix this issue. However the pull request is that to tag `v.0.1.0`. Then I cannot find a way to  make a pull request.
- I would appreciate if you could tell me to make the pull request.

**Comment by yoshida0112** [comment]
Thank you for your reply.

> Is this an issue you find with newer versions of TRTorch?

No, this issue exists only in v0.1.0. 

> v0.1.0 is almost a year old at this point, not sure if we want to patch it if its not an issue now. If you are constrained by your PyTorch or TensorRT choices, its pretty easy to change the dependencies (there might need to be one or two patches for PyTorch)

I am using old version of pytorch, and the migration to newer version of pytorch  is not easy because of some unresolved issues. 

Then I would be grateful if you could improve v0.1.0.

**Comment by narendasan** [comment]
Can you share the workspace file you are currently using? I'd much rather help you get 0.5.0a0 working with PyTorch 1.6 vs. patching a year old release.
