### ISSUE TITLE
🐛 [Bug] Encountered bug when using TRTorch

### ISSUE THREAD

**Issue by yokosyun** [NVIDIA/Torch-TensorRT#683]
##  Bug Description

when I import trtroch I get following error

```
python3
import trtorch
ModuleNotFoundError: No module named 'trtorch._C'
```

I built trtorch by
```
pip3 install -r requiment.txt
python3 setup.py install
```

I guess it try to import _C.py.  but I only found _C***.so in build folder

## Environment
 - TRTorch Version (0.4.0):  
 - PyTorch Version (1.9.1):
 - OS (Linux):
 - How you installed PyTorch (`pip`):
 - Python version: 3.6
 - CUDA version: 11.1
 - GPU models and configuration: RTX3080

**Comment by narendasan** [comment]
This might happen depending on the directory you are in. Make sure you are out of the TRTorch source tree and try importing, that is the case where I have seen this in the past. You should be able to relatively import just `_C` since it is a ffi extension, the .so file appears to python as a module
