### ISSUE TITLE
Compiling on Jetson Xavier with NVIDIA pytorch and cuda 10.2 fails; missing libcudart

### ISSUE THREAD

**Issue by quinn29** [NVIDIA/Torch-TensorRT#684]
I am trying to install TRTorch on the Jetson Xavier with Jetpack 4.6.
Both the torch and cuda installations work fine on their own.

I have commented out the "http_archive" lines and uncommented the "new_local_repository" lines in the WORKSPACE file, and I have changed the path to the cuda installation.

However, when trying to compile with `sudo bazel build //:libtrtorch --platforms //toolchains:jetpack_4.6` I get the following error.

`INFO: Build options --cxxopt, --define, and --linkopt have changed, discarding analysis cache.
INFO: Analyzed target //:libtrtorch (0 packages loaded, 2813 targets configured).
INFO: Found 1 target...
INFO: From Compiling cpp/bin/trtorchc/main.cpp:
cpp/bin/trtorchc/main.cpp: In function 'int main(int, char**)':
cpp/bin/trtorchc/main.cpp:340:18: warning: catching polymorphic type 'class args::Help' by value [-Wcatch-value=]
   } catch (args::Help) {
                  ^~~~
cpp/bin/trtorchc/main.cpp:343:29: warning: catching polymorphic type 'class args::ParseError' by value [-Wcatch-value=]
   } catch (args::ParseError e) {
                             ^
ERROR: /home/quinn29/.cache/bazel/_bazel_root/9161e410ccf95eb99b9534360aa0ca3e/external/cuda/BUILD.bazel:10:11: SolibSymlink _solib_aarch64/_U@cuda_S_S_Ccudart___Utargets_Sx86_U64-linux_Slib/libcudart.so failed: missing input file 'external/cuda/targets/x86_64-linux/lib/libcudart.so', owner: '@cuda//:targets/x86_64-linux/lib/libcudart.so'
Target //:libtrtorch failed to build   
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/quinn29/.cache/bazel/_bazel_root/9161e410ccf95eb99b9534360aa0ca3e/external/cuda/BUILD.bazel:10:11 SolibSymlink _solib_aarch64/_U@cuda_S_S_Ccudart___Utargets_Sx86_U64-linux_Slib/libcudart.so failed: 1 input file(s) do not exist
INFO: Elapsed time: 224.547s, Critical Path: 42.39s
INFO: 19 processes: 4 internal, 15 processwrapper-sandbox.
FAILED: Build did NOT complete successfully`

I have tried all other combinations of parameters I have seen, but I keep getting the same error.

**Comment by narendasan** [comment]
Have you tried clearing the bazel cache?
