### ISSUE TITLE
❓ [Question] TRtorch v0.1.0 does support aten::divonly?

### ISSUE THREAD

**Issue by yoshida-ryuhei** [NVIDIA/Torch-TensorRT#685]
## ❓ Question
I am trying to compile my model.
However compiler stops owing to a error.
Doss TRTorch v0.1.0 support `aten::divonly`?
Also, does the newer TRTorch support `aten::divonly`?

## What you have already tried
I searched the error messages at the internet.

## Environment
pytorch 1.6
TRTorch 0.1.0

## Additional context
The error message is this one.
```
>       compiled_cpp_mod = trtorch._C.compile_graph(module._c, _parse_compile_spec(compile_spec))
E       RuntimeError: [enforce fail at core/conversion/evaluators/NodeEvaluatorRegistry.cpp:56] Expected schema to be true but got false
E       Evaluator for aten::divonly runs on certain schemas, but schema for node is not retrievable
```

**Comment by narendasan** [comment]
I don't think we support divonly currently, we can look at adding support

**Comment by yoshida0112** [comment]
I found the function, I thought `aten::divonly`, is `aten::div`.
I am thinking about why the schema is not retrievable.
I would appreciate it if you let me know any advice to identify the reason.
