### ISSUE TITLE
why  https://github.com/NVIDIA/Torch-TensorRT/releases/torch_tensorrt-1.0.0-cp36-cp36m-linux_x86_64.whl depends on cuda 10.2 library

### ISSUE THREAD

**Issue by ylz1104** [NVIDIA/Torch-TensorRT#697]
why  https://github.com/NVIDIA/Torch-TensorRT/releases/torch_tensorrt-1.0.0-cp36-cp36m-linux_x86_64.whl depends on cuda 10.2 library

when I  try to install torch-tensorrt and import torch_tensorrt ,It was reported ImportError:libcudart.so.10.2: cannot open shared object file: No such file or directory

## Environment

> ImportError                               Traceback (most recent call last)
><ipython-input-1-291a947ced8e> in <module>
>----> 1 import torch_tensorrt
>
>/usr/local/python3/lib/python3.6/site-packages/torch_tensorrt/__init__.py in <module>
>      9
>     10 from torch_tensorrt._version import __version__
>---> 11 from torch_tensorrt._compile import *
>     12 from torch_tensorrt._util import *
>     13 from torch_tensorrt import ts
>
>/usr/local/python3/lib/python3.6/site-packages/torch_tensorrt/_compile.py in <module>
>      1 from typing import List, Dict, Any
>----> 2 from torch_tensorrt import _enums
>      3 import torch_tensorrt.ts
>      4 from torch_tensorrt import logging
>      5 import torch
>
>/usr/local/python3/lib/python3.6/site-packages/torch_tensorrt/_enums.py in <module>
>----> 1 from torch_tensorrt._C import dtype, DeviceType, EngineCapability, TensorFormat
>
>ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory

 - PyTorch Version (e.g., 1.0):torch_1.10+cu113
 - CPU Architecture: x86_64
 - OS (e.g., Linux): Centos 7
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pip3
 - Build command you used (if compiling from source): 
 - Are you using local sources or building from archives:
 - Python version: python3.6
 - CUDA version: cuda-11.3
 - GPU models and configuration:
 - Any other relevant information:

**Comment by narendasan** [comment]
@ylz1104 Thanks for catching this, the wrong binaries were uploaded. It should be fixed now

**Comment by narendasan** [comment]
@ylz1104 feel free to reopen if the issue persists
