### ISSUE TITLE
RuntimeError: Method (but not graphs in general) require a single output. Use None/Tuple for 0 or 2+ outputs

### ISSUE THREAD

**Issue by ylz1104** [NVIDIA/Torch-TensorRT#705]
RuntimeError: Method (but not graphs in general) require a single output. Use None/Tuple for 0 or 2+ outputs

when I compiled cpd-Resnet module, I set require_full_compile=False to avoid "aten::min.dim" and "aten::max.dim" that unsupported operators,It reported the above errors.Also , I set the final result with tuple type, but it no work

**Comment by ylz1104** [comment]
### **There is a part of torchscript graph that show tuple result**
![image](https://user-images.githubusercontent.com/22975054/141276231-8be35191-5af3-4c7c-81ee-312ce4bbdbbd.png)
### **There is a part of ts graph with compiled by torch_tensorrt**
![image](https://user-images.githubusercontent.com/22975054/141276735-fa912b8f-5cf7-4c39-9518-55775083aa7f.png)

I think it should be make tuple construct for final results if outputs size more than one

**Comment by narendasan** [comment]
can you set require_full_compile=True

**Comment by ylz1104** [comment]
The torchscript graph with unsupported operators aten::max.dim and aten::min.dim&nbsp;



发自我的iPhone


------------------ Original ------------------
From: Naren Dasan ***@***.***&gt;
Date: Thu,Nov 11,2021 11:48 PM
To: NVIDIA/Torch-TensorRT ***@***.***&gt;
Cc: ylz1104 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [NVIDIA/Torch-TensorRT] RuntimeError: Method (but not graphs ingeneral) require a single output. Use None/Tuple for 0 or 2+ outputs (Issue#705)





 
can you set require_full_compile=True
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by narendasan** [comment]
So there is definitely a bug with partial compilation that will take a bit to fix. But implementing support for min and max are trivial. If you want to run the model now I suggest following this tutorial: https://github.com/NVIDIA/Torch-TensorRT/tree/master/examples/custom_converters and use the existing min and max converters as reference: https://github.com/NVIDIA/Torch-TensorRT/blob/master/core/conversion/converters/impl/reduce.cpp. Or you can wait for us to get to these issues

**Comment by narendasan** [comment]
Also can you provide the full schemas for min.dim and max.dim?

**Comment by ylz1104** [comment]
> Also can you provide the full schemas for min.dim and max.dim?

![image](https://user-images.githubusercontent.com/22975054/141420135-4d38d031-0d30-41b3-a013-3571743e05be.png)
in_ is a torch tensor
