### ISSUE TITLE
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by anvarganiev** [NVIDIA/Torch-TensorRT#708]
I installed torch-tensorrt via pip: `pip3 install torch-tensorrt -f github.com/NVIDIA/Torch-TensorRT/releases`. And when I try to import it the _ImportError_ raises:
_ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory_
The full error:

```
ImportError                               Traceback (most recent call last)
<ipython-input-13-82536c89b207> in <module>
     13 from vision.utils.misc import str2bool, Timer, freeze_net_layers, store_labels
     14 
---> 15 import torch_tensorrt as torchtrt
     16 
     17 # import pytorch_quantization

~/.local/lib/python3.6/site-packages/torch_tensorrt/__init__.py in <module>
      9 
     10 from torch_tensorrt._version import __version__
---> 11 from torch_tensorrt._compile import *
     12 from torch_tensorrt._util import *
     13 from torch_tensorrt import ts

~/.local/lib/python3.6/site-packages/torch_tensorrt/_compile.py in <module>
      1 from typing import List, Dict, Any
----> 2 from torch_tensorrt import _enums
      3 import torch_tensorrt.ts
      4 from torch_tensorrt import logging
      5 import torch

~/.local/lib/python3.6/site-packages/torch_tensorrt/_enums.py in <module>
----> 1 from torch_tensorrt._C import dtype, DeviceType, EngineCapability, TensorFormat

ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
```

## Environment

 - PyTorch Version (e.g., 1.0): 1.10.0
 - CPU Architecture: x86_64
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pip3 install torch-tensorrt -f github.com/NVIDIA/Torch-TensorRT/releases
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version: 3.6
 - CUDA version: 10.2
 - GPU models and configuration: GeForce RTX 2080 Ti
 - Any other relevant information:

**Comment by narendasan** [comment]
I would make sure to verify that you have the right version of pytorch in your environment. You need to use PyTorch 1.10.0+cu113. Also its a bit concerning that your cuda version is 10.2. If you want to use 10.2 you should compile from source

**Comment by anvarganiev** [comment]
@narendasan, thanks for the answer! I checked with `pip3 list` my torch version, and it's just `torch 1.10.0`.  Now I updated it to torch 1.10.0+cu113, but there is another error raises now when importing torch-tensorrt:
`ImportError: libnvinfer_plugin.so.8: cannot open shared object file: No such file or directory`.
And I haven't seen anywhere that I should compile from source if I want to use cuda 10.2.

**Comment by narendasan** [comment]
We note our deps here https://github.com/NVIDIA/Torch-TensorRT#dependencies.

This error is because TensorRT is not in your LD_LIBRARY_PATH

**Comment by anvarganiev** [comment]
Thanks! I could import after changing cuda and TensorRT versions like in dependencies.

**Comment by dignakov** [comment]
I think I just submitted a bug for this same issue. Shouldn't all of the dependencies come with the wheel similar to the PyTorch install?

**Comment by semigok** [comment]
I had the similar problem. I think it is because of the compatibility issue with torch versions and the CUDA version you are using. CUDA is backwards compatible only withing the same main version such as 11.x or 9.x. If you install the wrong pytorch packages or wheel you can get this error.
