### ISSUE TITLE
🐛 [Bug] incompatible function arguments. 

### ISSUE THREAD

**Issue by XuanBaby** [NVIDIA/Torch-TensorRT#714]
##  Bug Description

 incompatible function arguments. 

## To Reproduce

https://github.com/NVIDIA/Torch-TensorRT/blob/master/tests/py/test_ptq_trt_calibrator.py

1.
1.

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

Torch-TensorRT Version (e.g. 1.0.0):
PyTorch Version (e.g. 1.10.0+cu113.):
CPU Architecture: x86
OS (e.g., Linux): Ubuntu 20.04.3 LTS
How you installed PyTorch (conda, pip, libtorch, source): conda
Build command you used (if compiling from source): bazel & python3 setup.py bdist_wheel
Are you using local sources or building from archives: using local sources
Python version: 3.8
CUDA version: 11.3
GPU models and configuration: A100
Any other relevant information:

## Additional context

`python3 test_ptq_trt_calibrator.py
Traceback (most recent call last):
  File "/work/Joanna/Torch_TensorRT/Torch-TensorRT-1.0.0/tests/py/test_ptq_trt_calibrator.py", line 118, in test_compile_script
    trt_mod = torchtrt.compile(self.model, **compile_spec)
  File "/opt/conda/lib/python3.8/site-packages/torch_tensorrt/_compile.py", line 97, in compile
    return torch_tensorrt.ts.compile(ts_mod, inputs=inputs, enabled_precisions=enabled_precisions, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch_tensorrt/ts/_compiler.py", line 119, in compile
    compiled_cpp_mod = _C.compile_graph(module._c, _parse_compile_spec(spec))
  File "/opt/conda/lib/python3.8/site-packages/torch_tensorrt/ts/_compile_spec.py", line 181, in _parse_compile_spec
    info.ptq_calibrator = compile_spec["calibrator"]
TypeError: (): incompatible function arguments. The following argument types are supported:
    1. (self: torch_tensorrt._C.ts.CompileSpec, arg0: torch_tensorrt._C.IInt8Calibrator) -> None
 
Invoked with: <torch_tensorrt._C.ts.CompileSpec object at 0x7effbc438170>, <test_ptq_trt_calibrator.TRTEntropyCalibrator object at 0x7effbc5036d0>`

**Comment by narendasan** [comment]
cc: @peri044
