### ISSUE TITLE
Prelu and arange bugs🐛 [Bug] Encountered bug when using Torch-TensorRT

### ISSUE THREAD

**Issue by ylz1104** [NVIDIA/Torch-TensorRT#720]
##  Bug Description

1. Prelu operator can not use normally，the output  data shape is incorrect.
2. aten::arange also with bugs that reports "upper bound and larger bound inconsistent with step sign".

## To Reproduce

![image](https://user-images.githubusercontent.com/22975054/141780826-57300033-5495-49bf-93c8-cd3f711049f3.png)

## Expected behavior

In my opinion, the official need check some evaluators and converter implements，maybe not pass all test cases.
## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0):v1.0.0
 - PyTorch Version (e.g. 1.0):1.10
 - CPU Architecture:x86_64
 - OS (e.g., Linux):Linux
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pip
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version:3.6.8
 - CUDA version:11.3
 - GPU models and configuration:
 - Any other relevant information:

**Comment by peri044** [comment]
Could you provide us python code which has your pytorch models (with input shapes) for us to reproduce?
