### ISSUE TITLE
I trained a model by libtorch,how to convert it to  tensorrt?

### ISSUE THREAD

**Issue by henbucuoshanghai** [NVIDIA/Torch-TensorRT#727]
by libtorch,not by pytorch.
how to convert the model to tensorrt?

**Comment by henbucuoshanghai** [comment]
by this repo?

**Comment by peri044** [comment]
What format is your trained model in ? You can try converting it into a torchscript module https://nvidia.github.io/Torch-TensorRT/tutorials/creating_torchscript_module_in_python.html and then use the torch_tensorrt [C++ API](https://nvidia.github.io/Torch-TensorRT/tutorials/getting_started_with_cpp_api.html) or [PythonAPI](https://nvidia.github.io/Torch-TensorRT/tutorials/getting_started_with_python_api.html)

**Comment by henbucuoshanghai** [comment]
pt
