### ISSUE TITLE
✨[Feature] Add an example of torchvision detection

### ISSUE THREAD

**Issue by zhiqwang** [NVIDIA/Torch-TensorRT#745]
**Describe the solution you'd like**

Add an example of TorchVision detection, such as the `SSDlite`: <https://pytorch.org/vision/stable/models.html#id60>.
```python
import torchvision
model = torchvision.models.detection.ssdlite320_mobilenet_v3_large(pretrained=True)
```
**Describe the solution you'd like**

I've seen there is an example of SSD <https://nvidia.github.io/Torch-TensorRT/_notebooks/ssd-object-detection-demo.html> which is released in NVIDIA/DeepLearningExamples, but its exported torchscript graph is a little different about the torchvision's.

**Describe alternatives you've considered**

**Additional context**

The models released by torchvision are friendly with torchscript. I think it will be better if there is also an example of the torchvision.

**Comment by narendasan** [comment]
What happens if you drop in SSDLite in place of SSD in the current example? Do you hit issues with conversion or something? Fundamentally the workflow is the same.

**Comment by zhiqwang** [comment]
Hi @narendasan ,

Thank you for your reply, I am sorry for not providing enough valid information here due to my experimental environment, I will close this issue first.

I will do some more extensive experiments and complement my own lab equipment, thanks for this awesome project.
