### ISSUE TITLE
🐛 [Bug] simple error compiling python

### ISSUE THREAD

**Issue by jinluyang** [NVIDIA/Torch-TensorRT#746]
##  Bug Description
Error compiling the python package:
https://github.com/NVIDIA/Torch-TensorRT#compiling-the-python-package
The error is:
py/../core/conversion/conversion.h:5:10: fatal error: NvInfer.h: No such file or directory
The error is due to the name changing from TRTorch to Torch-TensorRT.

## To Reproduce

do like this instuction: https://github.com/NVIDIA/Torch-TensorRT#compiling-the-python-package
1.cd py
2.python setup.py install --release

py/../core/conversion/conversion.h:5:10: fatal error: NvInfer.h: No such file or directory

## Expected behavior

success

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0):8.0
 - PyTorch Version (e.g. 1.0):1.10.0
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source):pip
 - Build command you used (if compiling from source):bazel build //:libtorchtrt --compilation_mode opt
 - Are you using local sources or building from archives: local sources
 - Python version:3.8
 - CUDA version:11.3

## Additional context

I know the problem is here:
https://github.com/NVIDIA/Torch-TensorRT/blob/09afccbbddf97adde4aa20399d495f81dd99bed1/py/setup.py#L242
just need to change "bazel-TRTorch" to "bazel-Torch-TensorRT", that solves my problem.
Someone please fix it because it is inconvenient for me to make a PR.

**Comment by narendasan** [comment]
Did this line not do this for you? https://github.com/NVIDIA/Torch-TensorRT/blob/09afccbbddf97adde4aa20399d495f81dd99bed1/py/setup.py#L244

**Comment by jinluyang** [comment]
> Did this line not do this for you?
> 
> https://github.com/NVIDIA/Torch-TensorRT/blob/09afccbbddf97adde4aa20399d495f81dd99bed1/py/setup.py#L244

Oh, sorry, it's because my repo has a different name.
