### ISSUE TITLE
🐛 [Bug] AddMMBranchFusion

### ISSUE THREAD

**Issue by samuellees** [NVIDIA/Torch-TensorRT#754]
##  Bug Description
The condition [here](https://github.com/NVIDIA/Torch-TensorRT/blob/master/core/lowering/passes/fuse_addmm_branches.cpp#L52) seems to be uncorrect.

It aims to merge two branches about _addmm_ and _matmul+add_ into one _addmm_, but why not equal to "_aten::add_"?

`    
if ((*arm1_start)->kind().toQualString() == std::string("aten::addmm") &&
        (*(++arm1_start))->kind() == prim::Return &&
        (*arm2_start)->kind().toQualString() == std::string("aten::matmul") &&
        (*(++arm2_start))->kind().toQualString() != std::string("aten::add") &&
        (*(++arm2_start))->kind() == prim::Return) {
      // Make sure that block0 is solely just the aten::addmm op and block1 is matmul + add
      return true;
}
`

**Comment by peri044** [comment]
Thanks for catching this.  Fixed in https://github.com/NVIDIA/Torch-TensorRT/pull/760
