### ISSUE TITLE
❓ [Question] Handling non-tensor input of module

### ISSUE THREAD

**Issue by DeriZSY** [NVIDIA/Torch-TensorRT#767]
## ❓ Question
Can `torch_tensorrt.compile` handle non-tensor input of the module (for example boolean and integer)? How should I do it?

**Comment by peri044** [comment]
I don't think we support non-tensor inputs. Can you share your model or usecase ?
Making those integer or bool input value as tensor in the pytorch module can be a temporary workaround.

**Comment by DeriZSY** [comment]
> I don't think we support non-tensor inputs. Can you share your model or usecase ? Making those integer or bool input value as tensor in the pytorch module can be a temporary workaround.

The integer input is used as an index to index some latent tensor within the network module. Otherwise, I'll need to have an extra wrapper to process those latent tensors and make them input of the main network module.
