### ISSUE TITLE
✨[Feature] Provide missing operators for YoloR

### ISSUE THREAD

**Issue by rodja** [NVIDIA/Torch-TensorRT#781]
**Is your feature request related to a problem? Please describe.**

While compiling [YOLOR](https://github.com/WongKinYiu/yolor.git), Torch-TensorRT reports the following missing opperators:

- `aten::Int.Tensor(Tensor a) -> (int)`
- `aten::div.Tensor_mode(Tensor self, Tensor other, *, str? rounding_mode) -> (Tensor)`
- `prim::PythonOp(...) -> (...)`
 

**Describe the solution you'd like**

I would like these converters to be available in Torch-TensorRT so I can run YoloR inferences.

**Describe alternatives you've considered**

I tried executing this operations with Torch instead of TensorRT by calling

```
ttrt_module = torch_tensorrt.compile(
    model,
    inputs=inputs,
    enabled_precisions=enabled_precisions,
    require_full_compilation=False,
    torch_executed_ops=['aten::Int', 'aten::div', 'prim::PythonOp'],
)
```

But the errors remained.

**Comment by rodja** [comment]
It looks like `aten::Int.Tensor(Tensor a)` is not so easy to implement: https://github.com/NVIDIA/Torch-TensorRT/issues/513

**Comment by narendasan** [comment]
Yeah we are working on a solution for aten::Int. The suggestion here is to try to help torchscript here with explicit casting if possible. We can work on aten::div.Tensor_mode. prim::PythonOp I dont think we can support. Partial compilation would be the only option here
