### ISSUE TITLE
🐛 [Bug] Installed torch_tensorrt using setup.py but encountered undefined symbol error

### ISSUE THREAD

**Issue by aeoleader** [NVIDIA/Torch-TensorRT#794]
##  Bug Description
Installed torch_tensorrt following [this](https://github.com/NVIDIA/Torch-TensorRT/tree/master/py) installation instruction. The installation is a success but when importing torch_tensorrt, it gives me the following error:
```error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/ssd01/anaconda3/envs/trtenv/lib/python3.8/site-packages/torch_tensorrt/__init__.py", line 11, in <module>
    from torch_tensorrt._compile import *
  File "/mnt/ssd01/anaconda3/envs/trtenv/lib/python3.8/site-packages/torch_tensorrt/_compile.py", line 2, in <module>
    from torch_tensorrt import _enums
  File "/mnt/ssd01/anaconda3/envs/trtenv/lib/python3.8/site-packages/torch_tensorrt/_enums.py", line 1, in <module>
    from torch_tensorrt._C import dtype, DeviceType, EngineCapability, TensorFormat
ImportError: /mnt/ssd01/anaconda3/envs/trtenv/lib/python3.8/site-packages/torch_tensorrt/lib/libtorchtrt.so: undefined symbol: _ZN2at11show_configB5cxx11Ev
```
## To Reproduce

Installation command used is the following
```bash
python setup.py install --use-cxx11-abi # without the cxx11 flag gives me error
```

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0): 1.0.0
 - PyTorch Version (e.g. 1.0): 1.10.1
 - CPU Architecture: x86_64
 - OS (e.g., Linux): ubuntu
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pip
 - Build command you used (if compiling from source): python setup.py install --use-cxx11-abi 
 - Are you using local sources or building from archives: local sources
 - Python version: 3.8
 - CUDA version: 11.5
 - GPU models and configuration: V100x4
 - Any other relevant information: using local cudnn(8.3.1)

**Comment by narendasan** [comment]
This is usually due to a C++ ABI issue. If you installed pytorch using `pip`, do not use the `--use-cxx11-abi` flag

**Comment by aeoleader** [comment]
> This is usually due to a C++ ABI issue. If you installed pytorch using `pip`, do not use the `--use-cxx11-abi` flag

If not using --use-cxx11-abi, I get the following error message:
```error
no such package '@libtorch_pre_cxx11_abi//': The repository '@libtorch_pre_cxx11_abi' could not be resolved and referenced by '//cpp/bin/torchtrtc:torchtrtc'
```

**Comment by narendasan** [comment]
In your WORKSPACE file, what is the entry for `libtorch_pre_cxx11_abi`?

**Comment by aeoleader** [comment]
> In your WORKSPACE file, what is the entry for `libtorch_pre_cxx11_abi`?

Got it. I am using local the "libtorch" repository instead of the "libtorch_pre_cxx11_abi" repository. Compilation works now. Thank you~

For anyone who tries to build torchtrt in a conda env using pip installed torch, here is the modification to the WORKSPACE file. 
```
new_local_repository(
    name = "libtorch_pre_cxx11_abi",
    path = ".../anaconda3/envs/trtenv/lib/python3.8/site-packages/torch/",
    build_file = "third_party/libtorch/BUILD"
)
```

**Comment by aeoleader** [comment]
Compilation and installation works, but importing gives me this error:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/ssd01/jayden.lxy/test_ground/Torch-TensorRT/py/torch_tensorrt/__init__.py", line 11, in <module>
    from torch_tensorrt._compile import *
  File "/mnt/ssd01/jayden.lxy/test_ground/Torch-TensorRT/py/torch_tensorrt/_compile.py", line 2, in <module>
    from torch_tensorrt import _enums
  File "/mnt/ssd01/jayden.lxy/test_ground/Torch-TensorRT/py/torch_tensorrt/_enums.py", line 1, in <module>
    from torch_tensorrt._C import dtype, DeviceType, EngineCapability, TensorFormat
ModuleNotFoundError: No module named 'torch_tensorrt._C'
```

**Comment by aeoleader** [comment]
> 

@narendasan Any help?

**Comment by narendasan** [comment]
Make sure to fully uninstall any existing versions of torch-tensorrt that are installed. Pip should return something like `package torch-tensorrt is not installed`. Sometimes multiple versions are laying around and mess up the import

**Comment by aeoleader** [comment]
> Make sure to fully uninstall any existing versions of torch-tensorrt that are installed. Pip should return something like `package torch-tensorrt is not installed`. Sometimes multiple versions are laying around and mess up the import

I create a new env and clean all bazel cache by running ```bazel clean```, but still get the undefined symbol error. What does this error mean? I checked a closed [thread](https://github.com/NVIDIA/Torch-TensorRT/issues/294), which indicates that the error may relate to a TensorRT path issue, but I have already added tensorrt to by LD_LIBRARY_PATH. Any idea what is the reason causing the error?

**Comment by aeoleader** [comment]
By the way, I have downgraded cudnn to 8.2 and tensorrt to 8.0.3.4.

**Comment by narendasan** [comment]
This part 
> ZN2at11show_configB5**cxx11**Ev

Implies that you compiled targeting the CXX11 Abi still. So some old build might still be installed

**Comment by chaoz-dev** [comment]
Did a quick grep through the `Torch-TensorRT` repo for the `show_config` function; looks like `core/util/build_info.h` is the only place this is called. This implies the symbol that you're looking for might be from this [file](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/Version.h).

So besides the instructions above regarding building with pre-C++11 ABI enabled, make sure you're also linking against the right PyTorch libraries (not just TensorRT as you've mentioned).

**Comment by p1x31** [comment]
Try `python3 -c "import torch_tensorrt; print(torch_tensorrt.__version__)"`
