### ISSUE TITLE
❓ [Question] Have anyone encounter this: RuntimeError: expected type comment but found 'eof' here

### ISSUE THREAD

**Issue by laisimiao** [NVIDIA/Torch-TensorRT#820]
## ❓ Question

when I run compile command like this:
```python
trt_ts_module = torch_tensorrt.compile(model,
                                inputs=[torch_tensorrt.Input((1, 3, 128, 128), dtype=torch.float32),
                                        torch_tensorrt.Input((1, 3, 320, 320), dtype=torch.float32)],
                                enabled_precisions = {torch.float, torch.half})
```
I encounter this error:
```
  File "/opt/conda/lib/python3.8/site-packages/torch/jit/frontend.py", line 310, in build_def
    type_comment_decl = torch._C.parse_type_comment(type_line)
RuntimeError: expected type comment but found 'eof' here:
#     # type: (List[Tensor], Tensor) -> Tensor
```

## What you have already tried

No other attempts.

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0): 1.11.0a0+b6df043
 - CPU Architecture: amd64
 - OS (e.g., Linux): ubuntu18.04
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pip
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version: 3.8
 - CUDA version: 11.5
 - GPU models and configuration: GTX 1660ti
 - Any other relevant information:

## Additional context

I just use docker recommended by tutorial at [https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch)

**Comment by narendasan** [comment]
Can you provide more context? Was your model already in TorchScript or are you letting TorchTRT handle that for you?
