### ISSUE TITLE
[Need Support] importing torch_tensorrt optimized model with trtorch

### ISSUE THREAD

**Issue by hanbrianlee** [NVIDIA/Torch-TensorRT#837]
Hi, I'm in a situation where I need to import torch_tensorrt(1.0) optimized model into trtorch0.4.1.

Is this supposed to work or is the optimized model generally not backwards compatible with previous trtorch/torch_tensorrt versions?

Thanks!

**Comment by narendasan** [comment]
This could be incompatible for a number of reasons. TorchScript IR changes every version of PyTorch so you are not guaranteed to be able to deserialize properly. If there was a TensorRT version switch you also would not be able to deserialize properly. Finally Torch-TensorRT has an internal "ABI" version that describes the serialization format for our embedded components which must match to deserialize. Both TensorRT and Torch-TensorRT will tell you if their parts are incompatible, if they are compatible they should work fine but TorchScript will not tell you, it will try to deserialize but you might hit bugs.  

So I would say you can try and see if you are lucky but usually this does not work.
