### ISSUE TITLE
🐛 [Bug] Can't use pip installation with standard Nvidia docker image

### ISSUE THREAD

**Issue by GiteZz** [NVIDIA/Torch-TensorRT#838]
##  Bug Description

When using the instructions on the release page to install the python module, I get 

`ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory`

on the import line.

```
FROM nvidia/cuda:11.3.1-cudnn8-devel-ubuntu20.04 
...
RUN pip install torch-tensorrt -f https://github.com/NVIDIA/Torch-TensorRT/releases
```

Use this base image and this installation method. When we then use `import torch_tensorrt` we get: `ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory` .

Full traceback:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/name/.local/lib/python3.8/site-packages/torch_tensorrt/__init__.py", line 11, in <module>
    from torch_tensorrt._compile import *
  File "/home/name/.local/lib/python3.8/site-packages/torch_tensorrt/_compile.py", line 2, in <module>
    from torch_tensorrt import _enums
  File "/home/name/.local/lib/python3.8/site-packages/torch_tensorrt/_enums.py", line 1, in <module>
    from torch_tensorrt._C import dtype, DeviceType, EngineCapability, TensorFormat
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
```
## Expected behavior

No error when importing.

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version: 1.0.0
 - PyTorch Version: 1.10.1
 - CPU Architecture: x86-64
 - OS (e.g., Linux): Ubuntu 20.04 docker on Ubuntu 20.04 base OS
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): `pip install torch==1.10.1 `
 - Build command you used (if compiling from source): /
 - Are you using local sources or building from archives: /
 - Python version: 3.8
 - CUDA version: 11.3.1
 - GPU models and configuration: RTX3000
 - Any other relevant information: /

**Comment by narendasan** [comment]
If I had to guess this is because you are probably not installing the correct version of pytorch. Try using 
```
pip3 install torch==1.10.2+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
```

**Comment by GiteZz** [comment]
That indeed solved the issue! Thanks for the help!
