### ISSUE TITLE
🐛 [Bug] Encountered bug when using Torch-TensorRT

### ISSUE THREAD

**Issue by contentis** [NVIDIA/Torch-TensorRT#840]
##  Bug Description
Broken link in the documentation: https://nvidia.github.io/Torch-TensorRT/tutorials/runtime.html#runtime
`An example of how to use libtorchtrt_runtime.so can be found here: https://github.com/NVIDIA/Torch-TensorRT/tree/master/examples/torchtrt_example`

## To Reproduce
https://github.com/NVIDIA/Torch-TensorRT/tree/master/examples/torchtrt_example
The link does not exist anymore

## Expected behavior
Should probably be replaced by:
https://github.com/NVIDIA/Torch-TensorRT/tree/master/examples/torchtrt_runtime_example

**Comment by narendasan** [comment]
@tanayvarshney Could you take a look at this?
