### ISSUE TITLE
How to set custom GCC path when compiling the source code

### ISSUE THREAD

**Issue by yuezhuang1387** [NVIDIA/Torch-TensorRT#852]
## ❓ Question
How to set the GCC path when compiling the source code

## What you have already tried
I try to build  Torch-TensorRT using locally installed cuDNN & TensorRT, But the following error occurred
![image](https://user-images.githubusercontent.com/61401199/152751388-e243228f-84f9-4761-8011-3f650adc91d0.png)
I found that this maybe a problem with the GCC version and needs to be upgraded, but the default /usr/bin/gcc requires root permission to change, I can't do anything about this path. So, I want to install a higher version of GCC in another path and specify the path of GCC when compiling Torch-TensorRT, but I don't know where to set the path of GCC.

**Comment by narendasan** [comment]
The best way would be to set up a bazel toolchain for your new compiler. https://docs.bazel.build/versions/main/toolchains.html. 
Here is an example of how we did this for a cross compiler in another project https://github.com/NVIDIA/DL4AGX/tree/master/toolchains/D5L. The important files are the BUILD and bzl files.

You could also try to override the CXX env variable but not sure if that would work in every case.
