### ISSUE TITLE
🐛 [Bug] gpt2 error using torch.jit.trace

### ISSUE THREAD

**Issue by Biaocsu** [NVIDIA/Torch-TensorRT#861]
##  Bug Description
```
/opt/conda/lib/python3.8/site-packages/transformers/models/gpt2/modeling_gpt2.py:196: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  attn_weights = attn_weights / (float(value.size(-1)) ** 0.5)
Traceback (most recent call last):
  File "generate_speed.py", line 282, in <module>
    tokenizer, eod_id, sep_id, unk_id, model = load_model()
  File "generate_speed.py", line 252, in load_model
    traced_model = torch.jit.trace(model, tokens)
  File "/opt/conda/lib/python3.8/site-packages/torch/jit/_trace.py", line 741, in trace
    return trace_module(
  File "/opt/conda/lib/python3.8/site-packages/torch/jit/_trace.py", line 958, in trace_module
    module._c._create_method_from_trace(
RuntimeError: Tracer cannot infer type of CausalLMOutputWithCrossAttentions(loss=None, logits=tensor([[[  1.6039, -14.8921, -12.7946,  ..., -12.5804, -13.8293, -13.4610],
         [ -1.9447, -17.5292, -15.7436,  ..., -15.3740, -17.2827, -16.3414],
         [ -2.1778, -15.4163, -13.4095,  ..., -12.6063, -14.2943, -14.2544],
         [ -1.2752, -13.6237, -12.9004,  ..., -12.0724, -11.4089, -11.1407]]],
       device='cuda:0'), past_key_values=((tensor([[[[ 1.3004e+00, -9.0571e-02, -1.1026e+00,  ..., -4.1700e-01,
            2.2270e-01, -1.0456e-02],
          [-1.3599e+00, -9.8881e-01,  3.2034e-01,  ...,  2.1444e-03,
...
[-4.8185e-01,  6.5437e-01, -1.7764e-01,  ...,  1.1841e+00,
            2.4035e-01,  7.0395e-01]]]], grad_fn=<PermuteBackward0>))), hidden_states=None, attentions=None, cross_attentions=None)
:Dictionary inputs to traced functions must have consistent type. Found Tensor and Tuple[Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor], Tuple[Tensor, Tensor]]
```

## To Reproduce

```
import torch
from transformers import GPT2Tokenizer, GPT2LMHeadModel

tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
model = GPT2LMHeadModel.from_pretrained('gpt2')
model.eval()

tokens=tokenizer('The cat is on the table.', return_tensors='pt')['input_ids']

with torch.jit.optimized_execution(True):
    traced_model = torch.jit.trace(model, tokens)

```
## Expected behavior

no error

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0): 1.1.0a0+c2025bc7
 - PyTorch Version (e.g. 1.0): 1.10.0a0+0aef44c
 - CPU Architecture:
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): `docker build --build-arg BASE=21.10 -f docker/Dockerfile -t torch_tensorrt:latest .`
 - Build command you used (if compiling from source):  `docker build --build-arg BASE=21.10 -f docker/Dockerfile -t torch_tensorrt:latest .`
 - Are you using local sources or building from archives:
 - Python version: 3.8.12
 - CUDA version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by narendasan** [comment]
This looks like an error from TorchScript and from your repro, seems like you aren't even importing torch-tensorrt. I would say just try using `torch.jit.script`. If you are still having issues, the PyTorch team is probably the best resource, perhaps asking the question on the PyTorch forums

**Comment by narendasan** [comment]
First thing I would try is to make sure your model is on GPU before compiling. These errors about op support may be misleading if partial compilation is enabled (which it is by default). But the Runtime error from PyTorch is caused by tensors not being on the same device. I think from there, you should be able to run, if not, we have dedicated support for some cases of aten::Int coming, as well as we can look at adding support for where.self
