### ISSUE TITLE
✨[Feature] Enable debug logging with a context 

### ISSUE THREAD

**Issue by narendasan** [NVIDIA/Torch-TensorRT#865]
**Is your feature request related to a problem? Please describe.**

Right now seems like users don't know how or don't enable debug logging. We can probably add some syntax to make this easier.

**Describe the solution you'd like**

I would love to see something like: 

```py
import torch_tensorrt as torchtrt 

with torchtrt.debug:
    torchtrt.ts.compile(....)

```

under the hood this would be equivalent to:

 ```py
import torch_tensorrt as torchtrt 

torchtrt.logging.set_reportable_log_level(torchtrt.logging.Level.Debug)
torchtrt.ts.compile(....)
torchtrt.logging.set_reportable_log_level(torchtrt.logging.Level.Error)
```

**Describe alternatives you've considered**

**Additional context**

**Comment by peri044** [comment]
In some other libraries, I've seen python functions accepting verbose=True as argument. Maybe one other option is to have 
torchtrt.ts.compile(....,, log_level = 'debug') defaulting it to info.

**Comment by chaoz-dev** [comment]
Agreed with the above... as `compile` is the primary entry point into torchtrt for most use cases, it would be highly ergonomic to enable verbosity through the same interface via an optional argument.

**Comment by narendasan** [comment]
Yeah I would agree except that, the logger covers not just the compilation step but also the execution step. Especially for the execution step there isn't a great access point to provide this argument. No reason we cant look at adding both.
