### ISSUE TITLE
🐛 [Bug] Error when building with Jetpack 4.6

### ISSUE THREAD

**Issue by jpdevicente** [NVIDIA/Torch-TensorRT#920]
##  Bug Description

On Jetson Xavier with Jetpack 4.6, cant build Torch-TensorRT with bazel or build it with python setup.

## To Reproduce

1. `bazel build //:libtorchtrt --platforms //toolchains:jetpack_4.6`
1. `python3 setup.py install`

Both lead to the same error:

INFO: Build options --compilation_mode, --cxxopt, --define, and 1 more have changed, discarding analysis cache.
INFO: Analyzed target //:libtorchtrt (24 packages loaded, 3204 targets configured).
INFO: Found 1 target...
ERROR: /home/robot/Torch-TensorRT/core/conversion/converters/BUILD:51:11: Compiling core/conversion/converters/impl/element_wise.cpp failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 57 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox
core/conversion/converters/impl/element_wise.cpp: In lambda function:
core/conversion/converters/impl/element_wise.cpp:347:104: error: 'kSIGN' is not a member of 'nvinfer1::UnaryOperation'
                       auto sign = ctx->net->addUnary(*tmp_div->getOutput(0), nvinfer1::UnaryOperation::kSIGN);
                                                                                                        ^~~~~
Target //:libtorchtrt failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 67.248s, Critical Path: 45.91s
INFO: 30 processes: 17 internal, 13 processwrapper-sandbox.
FAILED: Build did NOT complete successfully

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Jetpack 4.6
 - TensorRT Version: 8.0.1-1
 - Cuda 10.2
 - PyTorch Version 1.10.0 built from sratch

**Comment by narendasan** [comment]
Won't have access to a Xavier for a bit but to quickly check. Are you running Jetpack 4.6.0 or 4.6.1? If I had to guess at the root cause there, its probably because you have TRT 8.0 and we currently target 8.2 which should be available in 4.6.1. If you are on 4.6.0, would updating to 4.6.1 be feasible?

**Comment by ligaz** [comment]
Alternatively you can checkout the `v1.0.0` tag. It compiles successfully on Jetpack 4.6.0.

**Comment by jpdevicente** [comment]
Thank you for your replies! 

As @ligaz suggested, compiling with branch v1.0.0 worked, so I'll be using that.

**Comment by subella** [comment]
Hello,

Same problem. I tried compiling with v1.0.0 but got the following error:
`src/Torch-TensorRT/cpp/lib/BUILD:3:10: Linking cpp/lib/libtorchtrt_plugins.so failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc @bazel-out/aarch64-opt/bin/cpp/lib/libtorchtrt_plugins.so-2.params
`

I used local tensorrt and cudnn as shown in the compilation instructions and additionally modified this line in WORKSPACE to point to cuda 10.2:
`new_local_repository(
    name = "cuda",
    build_file = "@//third_party/cuda:BUILD",
    path = "/usr/local/cuda-10.2/",
)
`
