### ISSUE TITLE
✨[Feature] Support 2:4 Sparsity

### ISSUE THREAD

**Issue by calclavia** [NVIDIA/Torch-TensorRT#948]
**Is your feature request related to a problem? Please describe.**
Would be great if Torch TensorRT has support for TensorRT 8's feature:
https://developer.nvidia.com/blog/accelerating-inference-with-sparsity-using-ampere-and-tensorrt/

There is a flag right now on the docs
```
sparse_weights 
```
but it's unclear what this flag does and how it decides to use sparsity?

**Describe the solution you'd like**
A way to mark certain feed forward `nn.Linear`` layers as 2:4 sparse (after it is trained/fine-tuned as such). An easy way to enable it during model compilation.
Also, an example of how to use it in the docs would help.

**Comment by calclavia** [comment]
Ah, so it looks like if the weight matrix is 2:4 sparse (represented as a dense matrix), then TensorRT will auto optimize it?

**Comment by peri044** [comment]
Yes, if the sparsity flag is enabled. A sparse tactic for that layer will only be picked if it’s the fastest

**Comment by calclavia** [comment]
Thanks for the info!
